"""empty message

Revision ID: 119677033156
Revises: 
Create Date: 2020-08-28 15:50:24.306044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119677033156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.Column('server', sa.String(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###
