"""empty message

Revision ID: 435f883503f0
Revises: 638da84bb22b
Create Date: 2020-09-03 13:48:23.725176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '435f883503f0'
down_revision = '638da84bb22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('muted_id', sa.Integer(), nullable=True),
    sa.Column('muter_id', sa.Integer(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mutes')
    # ### end Alembic commands ###
