"""empty message

Revision ID: 638da84bb22b
Revises: c7039831d754
Create Date: 2020-09-01 23:35:09.913361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638da84bb22b'
down_revision = 'c7039831d754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('unmuted_role_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'unmuted_role_id')
    # ### end Alembic commands ###
