"""empty message

Revision ID: c7039831d754
Revises: 119677033156
Create Date: 2020-08-31 20:28:15.502190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7039831d754'
down_revision = '119677033156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('muted_role_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    # ### end Alembic commands ###
