"""empty message

Revision ID: d4e3cb486f17
Revises: 435f883503f0
Create Date: 2020-09-03 15:15:36.104688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e3cb486f17'
down_revision = '435f883503f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutes', sa.Column('channel_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mutes', 'channel_id')
    # ### end Alembic commands ###
